package com.charity.app.model;

import com.charity.app.model.enums.UserRole;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * One uploaded document attached to a request.
 *
 * <p>Replaces the bare filename that {@code requests.documents_json} used to hold. The stored name
 * is a UUID generated by {@code FileStorageService} and is never exposed directly -- the DTO serves
 * {@code AppUrls.fileUrl(storedFilename)} instead.
 *
 * <p>Nothing here may identify the beneficiary. The uploader confirms that in the panel before the
 * first upload; the remedy if it happens anyway is deletion of the row and the file, which is what
 * makes deletion here hard rather than soft.
 */
@Entity
@Table(name = "request_documents")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RequestDocument {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "request_id", nullable = false)
    private Request request;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    private DocumentCategory category;

    /** Generated UUID name on disk. Never shown; never taken from the uploader. */
    @Column(name = "stored_filename", nullable = false)
    private String storedFilename;

    /** The name the uploader's file had, for display only. */
    @Column(name = "original_filename")
    private String originalFilename;

    /** Optional label typed by the uploader; only honoured when a single file is posted. */
    private String title;

    @Column(name = "content_type", length = 120)
    private String contentType;

    @Column(name = "size_bytes")
    private Long sizeBytes;

    @Column(name = "sort_order", nullable = false)
    @Builder.Default
    private int sortOrder = 0;

    /** Who attached it. Only a centre uploads to a request; an admin has delete only. */
    @Enumerated(EnumType.STRING)
    @Column(name = "uploaded_by_role", length = 16)
    private UserRole uploadedByRole;

    @CreationTimestamp
    @Column(name = "uploaded_at", updatable = false)
    private LocalDateTime uploadedAt;
}
