spring:
  application:
    name: charity-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/charity?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Tehran&characterEncoding=utf8&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:a-very-long-random-string-at-least}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
  channel: ${TELEGRAM_CHANNEL:}
  enabled: ${TELEGRAM_ENABLED:false}

bale:
  bot-token: ${BALE_BOT_TOKEN:573415822:G7Y6X1umfpGT_eU4_9lNDfp0AnvV4aIebhM}
  channel: ${BALE_CHANNEL:@yariju}
  enabled: ${BALE_ENABLED:true}

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost,http://127.0.0.1,http://localhost:5173,http://127.0.0.1:5173}

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

app:
  base-url: ${APP_BASE_URL:http://localhost:8082}
