package com.charity.app.controller;

import com.charity.app.common.AppUrls;
import com.charity.app.model.Request;
import com.charity.app.model.enums.CenterStatus;
import com.charity.app.repository.CenterRepository;
import com.charity.app.service.CategoryService;
import com.charity.app.service.RequestService;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.http.CacheControl;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.time.Duration;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;

/**
 * Feeds the sitemap.
 *
 * <p>The XML itself is generated by the frontend rather than here. The canonical hostname and the
 * URL shape are frontend concerns -- having the API hardcode {@code /requests/{slug}} and the public
 * host would guarantee the two drift apart -- so this exposes the raw entries and lets the site
 * render them.
 */
@RestController
@RequestMapping("/api/public/sitemap")
@RequiredArgsConstructor
public class SeoController {

    /** Kept well under the 50k sitemap limit so the frontend can map pages 1:1 onto sitemap files. */
    private static final int MAX_PAGE_SIZE = 5000;

    private final RequestService requests;
    private final CenterRepository centers;
    private final CategoryService categories;
    private final AppUrls urls;

    public record SitemapEntry(String path, OffsetDateTime lastModified, double priority) {
    }

    @GetMapping("/index")
    public ResponseEntity<Map<String, Object>> index() {
        long requestCount = requests.indexable(PageRequest.of(0, 1)).getTotalElements();
        long centerCount = centers.findIndexable(CenterStatus.APPROVED, PageRequest.of(0, 1)).getTotalElements();
        return cached(Map.of(
                "requests", Map.of("total", requestCount, "pageSize", MAX_PAGE_SIZE),
                "centers", Map.of("total", centerCount, "pageSize", MAX_PAGE_SIZE),
                "categories", Map.of("total", (long) categories.listActive().size(), "pageSize", MAX_PAGE_SIZE)));
    }

    @GetMapping("/requests")
    public ResponseEntity<List<SitemapEntry>> requests(@RequestParam(defaultValue = "0") int page,
                                                       @RequestParam(defaultValue = "5000") int size) {
        Page<Request> found = requests.indexable(PageRequest.of(Math.max(page, 0), clamp(size)));
        return cached(found.getContent().stream()
                .map(request -> new SitemapEntry(
                        "/requests/" + request.getSlug(),
                        urls.iso(request.getUpdatedAt()),
                        0.8))
                .toList());
    }

    @GetMapping("/centers")
    public ResponseEntity<List<SitemapEntry>> centers(@RequestParam(defaultValue = "0") int page,
                                                      @RequestParam(defaultValue = "5000") int size) {
        return cached(centers.findIndexable(CenterStatus.APPROVED,
                        PageRequest.of(Math.max(page, 0), clamp(size), Sort.by("id")))
                .getContent().stream()
                .map(center -> new SitemapEntry(
                        "/centers/" + center.getSlug(),
                        urls.iso(center.getUpdatedAt()),
                        0.6))
                .toList());
    }

    @GetMapping("/categories")
    public ResponseEntity<List<SitemapEntry>> categories() {
        return cached(categories.listActive().stream()
                .map(category -> new SitemapEntry(
                        "/requests/category/" + category.slug(),
                        category.updatedAt(),
                        0.7))
                .toList());
    }

    private static int clamp(int size) {
        return Math.min(Math.max(size, 1), MAX_PAGE_SIZE);
    }

    private <T> ResponseEntity<T> cached(T body) {
        return ResponseEntity.ok()
                .cacheControl(CacheControl.maxAge(Duration.ofMinutes(30)).cachePublic())
                .body(body);
    }
}
